### niepoprawny zapis
POST http://localhost:8080/rest/api/clients
Accept: application/json

### dodanie jednego
POST http://localhost:8080/rest/api/clients/
Accept: application/json
Content-Type: application/json

{
  "login":"test_2login",
  "firstName":"TestFirstName",
  "lastName":"TestLastName",
  "address": {
    "city":"Lipinki Łużyckie",
    "street":"Łączna",
    "streetNr":"43"
  }
}



### add fake client
POST http://localhost:8080/rest/api/clients/addFake
Accept: application/json


### add fake admin
POST http://localhost:8080/rest/api/admins/addFake
Accept: application/json

### add fake employee
POST http://localhost:8080/rest/api/admins/addFake
Accept: application/json




### get all clients
GET http://localhost:8080/rest/api/clients?login=MkZsS6vH1KLHLB5BVlGujqT32HB6RW
Accept: application/json

### get clients by login
GET http://localhost:8080/rest/api/clients?login=test_2
Accept: application/json

### get one client
GET http://localhost:8080/rest/api/clients/2d527738-aeaa-4865-af15-019d4da0b4ad
Accept: application/json

### get one client by login
GET http://localhost:8080/rest/api/clients/SpAIAcC
Accept: application/json




### update one client
PUT http://localhost:8080/rest/api/clients/deff6eab-75cf-46f9-87b4-660055677324
Accept: application/json
Content-Type: application/json

{
  "login": "EcG8X45",
  "address": {
    "city": "Lipinki Luzyckie",
    "street": "Laczna",
    "streetNr": "43"
  },
  "firstName": "otherFname",
  "lastName": "TestLastName"
}


