version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
  db2:
    image: postgres:14
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - 5433:5432
    volumes:
      - pg2:/var/lib/postgresql/data
  test:
    image: postgres:14
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - 5554:5432
    volumes:
      - pgTest:/var/lib/postgresql/data

  rabbit:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_DEFAULT_USER=nbd
      - RABBITMQ_DEFAULT_PASS=nbdpassword
    ports:
      # communication
      - '5672:5672'
      # browser UI
      - '15672:15672'
volumes:
  pg:
  pg2:
  pgTest:
